server:
  port: 10003
spring:
  application:
    name: consumer-feign
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.123:8888/eureka/
# 开启断路器
feign:
  hystrix:
    enabled: true