# 端口设置
server:
  port: 8083
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.122:3306/miscellaneous_quartz?characterEncoding=UTF-8&useSSL=false&useUnicode=true
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update # ddl-auto:设为update表示每次都不会重新建表
    show-sql: false
  application:
    name: quartz-cluster
#####################################################################################################
  # flyway 设置
  flyway:
    baseline-on-migrate: true
#####################################################################################################
# 打印日志
#logging:
#  level:
#    root: INFO
#    org.hibernate: INFO
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
#    com.springms: DEBUG
logging:
  config: classpath:logback.xml